version: '3.7'

services:
    web:
        container_name: backend_app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - './server:/var/www/html'
            - '/var/www/html/vendor'
        ports:
            - "8000:80" # web
            - "2222:22" # ssh
        links:
            - mysql

    mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
        restart: unless-stopped
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ~/volumes/mysql:/var/lib/mysql

    frontend:
        container_name: frontend
        build:
          context: .
          dockerfile: node.Dockerfile
        volumes:
          - './frontend:/app'
          - '/app/node_modules'
        ports:
          - '3000:3000'
        environment:
          - NODE_ENV=development
